Week 03 Reflection Contribution from mresendiz3-stat697
stat697-s19/course-questions-wiki pull request #63
Opened 2019-02-15 04:04 UTC by mresendiz3-stat697

2019-02-15 15:26 UTC, prof-lankham requested changes
Please update PR, adding author attribution to all answers, and DM me in Slack with PR URL when ready for re-evaluation.

2019-02-15 15:26 UTC, prof-lankham commented on week-03-reflections/mresendiz3-stat697.md
> +* Answer: Use inner join with columns that have the same data type. The columns don't necessarily need to have the same name.
Answers should also have author attributions

2019-02-18 04:28 UTC, mresendiz3-stat697 commented on week-03-reflections/mresendiz3-stat697.md
> +* Answer: Use inner join with columns that have the same data type. The columns don't necessarily need to have the same name.
Author attributions added; thanks!

2019-02-18 04:31 UTC, mariano-resendiz reviewed
Author attribution added.

2019-02-18 19:27 UTC, prof-lankham requested changes
Please update PR, adding author attribution to all answers, and DM me in Slack with PR URL when ready for re-evaluation.

2019-02-18 19:27 UTC, prof-lankham commented on week-03-reflections/mresendiz3-stat697.md
> +* Answer: Use inner join with columns that have the same data type. The columns don't necessarily need to have the same name.
Author attribution means to put your GitHub user name in parentheses after each Question/Answer, which you're currently only doing with Questions.

2019-02-18 19:27 UTC, prof-lankham commented on week-03-reflections/mresendiz3-stat697.md
> +* Author attribution: SAS Institute Inc. 2014. SAS� Certification Prep Guide: Advanced Programming for SAS�9, Fourth Edition. Cary, NC: SAS Institute Inc.
Citing the textbook is not necessary.

2019-02-20 01:14 UTC, mresendiz3-stat697 commented on week-03-reflections/mresendiz3-stat697.md
> +* Author attribution: SAS Institute Inc. 2014. SAS� Certification Prep Guide: Advanced Programming for SAS�9, Fourth Edition. Cary, NC: SAS Institute Inc.
I took the citation off and added the author attribution to the W3RC.

2019-02-20 01:17 UTC, merged